/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiAhorcado;

import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Estudiantes
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }
    Palabra1 palabra = new Palabra1();
    JLabel casilla[];
    String PalabraSeleccionada = "";

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        A = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        H = new javax.swing.JButton();
        W = new javax.swing.JButton();
        E = new javax.swing.JButton();
        R = new javax.swing.JButton();
        F = new javax.swing.JButton();
        V = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        T = new javax.swing.JButton();
        B = new javax.swing.JButton();
        N = new javax.swing.JButton();
        G = new javax.swing.JButton();
        S = new javax.swing.JButton();
        X = new javax.swing.JButton();
        U = new javax.swing.JButton();
        I = new javax.swing.JButton();
        M = new javax.swing.JButton();
        J = new javax.swing.JButton();
        O = new javax.swing.JButton();
        L = new javax.swing.JButton();
        K = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Ñ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("JUGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Q.setText("Q");
        Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QMouseClicked(evt);
            }
        });

        Z.setText("Z");

        A.setText("A");

        Y.setText("Y");

        H.setText("H");

        W.setText("W");
        W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WMouseClicked(evt);
            }
        });

        E.setText("E");

        R.setText("R");

        F.setText("F");

        V.setText("V");

        C.setText("C");

        D.setText("D");

        T.setText("T");

        B.setText("B");

        N.setText("N");

        G.setText("G");

        S.setText("S");

        X.setText("X");

        U.setText("U");

        I.setText("I");

        M.setText("M");

        J.setText("J");

        O.setText("O");

        L.setText("L");

        K.setText("K");

        P.setText("P");

        Ñ.setText("Ñ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(S)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(F)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G)
                        .addGap(7, 7, 7)
                        .addComponent(H)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ñ)
                        .addGap(362, 362, 362))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Z)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X)
                                .addGap(13, 13, 13)
                                .addComponent(C)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(M))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(W)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E)
                                .addGap(9, 9, 9)
                                .addComponent(R)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(T)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(O)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(338, 338, 338))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q)
                    .addComponent(W)
                    .addComponent(E)
                    .addComponent(R)
                    .addComponent(T)
                    .addComponent(Y)
                    .addComponent(U)
                    .addComponent(I)
                    .addComponent(O)
                    .addComponent(P))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(F)
                    .addComponent(D)
                    .addComponent(S)
                    .addComponent(G)
                    .addComponent(H)
                    .addComponent(J)
                    .addComponent(K)
                    .addComponent(L)
                    .addComponent(Ñ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Z)
                    .addComponent(V)
                    .addComponent(C)
                    .addComponent(X)
                    .addComponent(B)
                    .addComponent(N)
                    .addComponent(M))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        PalabraSeleccionada = palabra.mipalabrita();
        casilla = new JLabel[PalabraSeleccionada.length()];
        
        
        for (int i = 0; i < PalabraSeleccionada.length(); i++) {
            
            casilla[i]=new JLabel();
            casilla[i].setBounds(18 * i, 40, 20, 30);
            casilla[i].setSize(new Dimension(50,50));
            casilla[i].setText("-");
            //casilla[i].setText(String.valueOf(palabrita.charAt(i)));
            this.add(casilla[i]);
            casilla[i].setVisible(true);
        }
       this.repaint();
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QMouseClicked
     
         ValidarLetra("q");
    }
    
    
    public void ValidarLetra(String letra){
    String qletter = letra;
    int contadorErrores = 0;
    String palabrita = PalabraSeleccionada;
    
    if(contadorErrores < 5){
    for (int n = 0; n < palabrita.length(); n++) {
         char c = palabrita.charAt(n); 
         
         if(String.valueOf(c).equals(qletter)){
             System.out.println("la posicion es"+n); 
             System.out.println(c); 
             casilla[n]=new JLabel();
             casilla[n].setBounds(18 * n, 30, 20, 30);
             casilla[n].setSize(new Dimension(50,50));
             // casilla[i].setText("-");
             casilla[n].setText(letra);
             this.add(casilla[n]);
             casilla[n].setVisible(true);             
         }else{
         contadorErrores++;
         
         //agregar dibujo
         }         
       }  
      }else{
    
    //perdio
    
    }
  
    // char [] aPalabrita = palabrita.toCharArray();
   this.repaint();
     /*for (int i = 0; i<palabrita.length(); i++){
       String letra = String.valueOf(palabrita.charAt(i));
       if(letra.equals(qletter)){
           
            casilla[i]=new JLabel();
            casilla[i].setBounds(18 * i, 40, 20, 30);
            casilla[i].setSize(new Dimension(50,50));
           // casilla[i].setText("-");
            casilla[i].setText("q");
            this.add(casilla[i]);
            casilla[i].setVisible(true);
       }
       this.repaint();*/
    }//GEN-LAST:event_QMouseClicked

    private void WMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WMouseClicked
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton Ñ;
    // End of variables declaration//GEN-END:variables
}
